development: &default
  adapter: mysql
  database: trainingday_development
  username: root
  password:
  host: localhost
  encoding: utf8
  socket: <%= ["/tmp/mysqld.sock",
       "/tmp/mysql.sock",
       "/var/run/mysqld/mysqld.sock",
      "/var/lib/mysql/mysql.sock"].detect{|socket|
      File.exist?(socket)
      } %>


test: &test
  <<: *default
  database: trainingday_test


cucumber:
  <<: *test